### PR TITLE
Use Systemd if installed

### PR DESCRIPTION
**Pull request by WinterNis**
Check if services are managed with systemd. If that's the case, use beamium.service config file and systemctl commands. It still works if systemd is not installed.

### CODE REVIEW

**Comment by WinterNis** [comment]
The way of checking systemd installation is not reliable. I'm currently changing it. -----> Changed , it's better now.

**Comment by d33d33** [comment]
Thanks!
What happened to the init.d file if systemd is present?

**Comment by WinterNis** [comment]
@d33d33 : If the system does not have systemd, it still works with sysv. If systemd is installed then beamium.service file is used to setup service. init.d beamium file is still loaded in /etc/init.d/. 
Init.d file is still necessary for compatibility (this is the only reason I forced myself to test the installation on os without systemd ;) . I hope this clarify the question.

**Comment by d33d33** [comment]
Loading the init.d if unused is confusing no?

**Comment by WinterNis** [comment]
It might be. The goal was to ensure compatibility for people who are already using beamium.

**Comment by d33d33** [comment]
Upgrade can be managed by the package. Spawning unused files is confusing for users ;)

**Pull request closed without merging**
